CREATE TABLE OPERATION ( 
	oper_name varchar(50) NOT NULL,
	oper_desc varchar(50)
)
;

ALTER TABLE OPERATION
	ADD CONSTRAINT UQ_OPERATION_oper_name UNIQUE (oper_name)
;

ALTER TABLE OPERATION ADD CONSTRAINT PK_OPERATION 
	PRIMARY KEY CLUSTERED (oper_name)
;



