CREATE TABLE USER_GR ( 
	name varchar(50) NOT NULL,
	gr_name varchar(50) NOT NULL
)
;

ALTER TABLE USER_GR ADD CONSTRAINT PK_USER_GR 
	PRIMARY KEY CLUSTERED (name, gr_name)
;

ALTER TABLE USER_GR ADD CONSTRAINT FK_gr_name 
	FOREIGN KEY (gr_name) REFERENCES GROUP (gr_name)
;

ALTER TABLE USER_GR ADD CONSTRAINT FK_name 
	FOREIGN KEY (name) REFERENCES USER (name)
;



