CREATE TABLE GR_OPER ( 
	oper_name varchar(50) NOT NULL,
	gr_name varchar(50) NOT NULL
)
;

CREATE TABLE GROUP ( 
	gr_name varchar(50) NOT NULL,
	gr_desc varchar(50)
)
;

CREATE TABLE OPERATION ( 
	oper_name varchar(50) NOT NULL,
	oper_desc varchar(50)
)
;

CREATE TABLE USER ( 
	name varchar(50) NOT NULL,
	password varchar(50) NOT NULL
)
;

CREATE TABLE USER_GR ( 
	name varchar(50) NOT NULL,
	gr_name varchar(50) NOT NULL
)
;

CREATE TABLE USER_OPER ( 
	name varchar(50) NOT NULL,
	oper_name varchar(50) NOT NULL
)
;


ALTER TABLE GROUP
	ADD CONSTRAINT UQ_GROUP_gr_name UNIQUE (gr_name)
;

ALTER TABLE OPERATION
	ADD CONSTRAINT UQ_OPERATION_oper_name UNIQUE (oper_name)
;

ALTER TABLE USER
	ADD CONSTRAINT UQ_USER_name UNIQUE (name)
;

ALTER TABLE GR_OPER ADD CONSTRAINT PK_GR_OPER 
	PRIMARY KEY CLUSTERED (oper_name, gr_name)
;

ALTER TABLE GROUP ADD CONSTRAINT PK_GROUP 
	PRIMARY KEY CLUSTERED (gr_name)
;

ALTER TABLE OPERATION ADD CONSTRAINT PK_OPERATION 
	PRIMARY KEY CLUSTERED (oper_name)
;

ALTER TABLE USER ADD CONSTRAINT PK_USER 
	PRIMARY KEY CLUSTERED (name)
;

ALTER TABLE USER_GR ADD CONSTRAINT PK_USER_GR 
	PRIMARY KEY CLUSTERED (name, gr_name)
;

ALTER TABLE USER_OPER ADD CONSTRAINT PK_USER_OPER 
	PRIMARY KEY CLUSTERED (name, oper_name)
;



ALTER TABLE GR_OPER ADD CONSTRAINT FK_gr_name 
	FOREIGN KEY (gr_name) REFERENCES GROUP (gr_name)
;

ALTER TABLE GR_OPER ADD CONSTRAINT FK_oper_name 
	FOREIGN KEY (oper_name) REFERENCES OPERATION (oper_name)
;

ALTER TABLE USER_GR ADD CONSTRAINT FK_gr_name 
	FOREIGN KEY (gr_name) REFERENCES GROUP (gr_name)
;

ALTER TABLE USER_GR ADD CONSTRAINT FK_name 
	FOREIGN KEY (name) REFERENCES USER (name)
;

ALTER TABLE USER_OPER ADD CONSTRAINT FK_name 
	FOREIGN KEY (name) REFERENCES USER (name)
;

ALTER TABLE USER_OPER ADD CONSTRAINT FK_oper_name 
	FOREIGN KEY (oper_name) REFERENCES OPERATION (oper_name)
;
