<?xml version="1.0" encoding="utf-8"?><Database Name="proba" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=L418-RA01\SQLEXPRESS;Initial Catalog=proba;Integrated Security=True;Pooling=False" SettingsObjectName="DAC.Properties.Settings" SettingsPropertyName="probaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table1" Member="Table1s">
    <Type Name="Table1">
      <Column Name="nr" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="id" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Table2_Table1" Member="Table2" ThisKey="id" OtherKey="id" Type="Table2" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Table2" Member="Table2s">
    <Type Name="Table2">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="typ" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Table2_Table1" Member="Table1s" ThisKey="id" OtherKey="id" Type="Table1" />
    </Type>
  </Table>
</Database>