ALTER TABLE GR_OPER ADD CONSTRAINT FK_oper_name 
	FOREIGN KEY (oper_name) REFERENCES OPERATION (oper_name)
;
GO
ALTER TABLE USER_OPER ADD CONSTRAINT FK_oper_name 
	FOREIGN KEY (oper_name) REFERENCES OPERATION (oper_name)
;


